plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version "${neo_gradle}"
    id "me.modmuss50.mod-publish-plugin" version "${modmuss_publish}"
}

def ENV = System.getenv()
version = "${ENV.GITHUB_RUN_NUMBER}" ? "${mod_version}.${ENV.GITHUB_RUN_NUMBER}" : "${mod_version}.nobuildnumber"
group = project.maven_group

repositories {
    mavenLocal()
    maven {
        url "https://cursemaven.com"
    }
    maven {
        url 'https://maven.blamejared.com'
    }
    maven {
        url 'https://maven.nanite.dev/'
    }
    maven {
        url 'https://maven.ftb.dev/releases'
    }
    maven {
        url 'https://maven.architectury.dev/'
    }
    maven {
        url 'https://api.modrinth.com/maven'
    }
}

base {
    archivesName = project.archives_base_name + "-neo"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.archives_base_name
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.archives_base_name
        programArgument '--nogui'
    }

    data {
        programArguments.addAll '--mod', project.archives_base_name, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { 
    srcDir 'src/generated/resources'
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
    runtimeOnly "curse.maven:jei-238222:5781938" //Just Enough Items
    runtimeOnly "curse.maven:architectury-419699:5786327"
    runtimeOnly "curse.maven:toolkit-324888:5521502"
    runtimeOnly "dev.ftb.mods:ftb-library-neoforge:2100.1.4"
    implementation "maven.modrinth:jade:${jade_version}+neoforge"
}
tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            version: version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

publishMods {
    dryRun = providers.environmentVariable("CURSE_DEPLOY").getOrNull() == null
    file = jar.archiveFile
    modLoaders.add("neoforge")
    type = BETA
    changelog = "changeme"
    displayName = "${mod_name} v${project.version} - NeoForge - ${minecraft_version}"
    curseforge {
        accessToken = providers.environmentVariable("CURSE_DEPLOY")
        projectId = project.curseforge_id
        minecraftVersions.add("Java 21")
        minecraftVersions.add("${minecraft_version}")
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}