modLoader = "javafml" #mandatory
loaderVersion = "[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
issueTrackerURL = "https://github.com/manmaed/PetSlow/issues" #optional
[[mods]] #mandatory
modId = "petslow" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "PetSlow" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/manmaed/PetSlow/main/update.json" #optional
credits = "Wendi for the SlowDoll and Riz for the death sound" #optional
authors = "manmaed" #optional
description = '''
Mini Slowpokes!'''