modLoader = "javafml"
loaderVersion = "[49,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/manmaed/PetSlow/issues" #optional
[[mods]]
modId = "petslow"
version="${version}"
displayName = "PetSlow"
updateJSONURL = "https://raw.githubusercontent.com/manmaed/PetSlow/main/update.json" #optional
credits = "Wendi for the SlowDoll and Riz for the death sound"
authors = "manmaed"
description = '''Mini Slowpokes!'''
[[dependencies.petslow]]
modId="forge"
mandatory=true
versionRange="[49.0.3,)"
ordering="NONE"
side="BOTH"